# Generated by Django 4.2 on 2023-04-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='start_count',
            new_name='star_count',
        ),
    ]
