# Generated by Django 4.2 on 2023-05-02 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_wishtitem_customer_basketitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basketlist', to='customer.customer'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('discount', models.FloatField()),
                ('expire', models.DateTimeField()),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used_customers', models.ManyToManyField(related_name='used_coupons', to='customer.customer')),
            ],
        ),
    ]
