# Generated by Django 4.2 on 2023-05-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_resetpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
